Homework06 - Numpy

By Antoaneta Chakarova for Geog592

09/24/2026

1. What value is returned by locations[0]

Oak

2. What value is returned by locations[4]

Elm

3. What values are returned by locations[1:4]

Pine, Maple, and Cedar

In [ ]:
locations = ["Oak", "Pine", "Maple", "Cedar", "Elm"]
locations[2] #4. Indexing expression that returns Maple

'Maple'

5. What does points[2] return

[180, 260]

6. What does points[2][1] return? Explain what each index selects

Returns 260, where the first index selects the third point and the second index selects its y-coordinate

In [2]:
points_list = [[100, 200], [140, 230], [180, 260], [120, 280]]
points_list[1][0] #7. Return the x-coordinate of the second point

140

8. What type of object is returned by df["ft"]

A pandas Series

In [3]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Oak", "Pine", "Maple", "Cedar"],
    "ft": [25, 48, 31, 60],
    "zone": ["A", "B", "A", "B"]
})

df[["name", "ft"]] #9. Select the name and ft columns together

,name,ft
0,Oak,25
1,Pine,48
2,Maple,31
3,Cedar,60


10. What row is returned by df.iloc[1]

The second row, containing Pine, 48, and B

In [4]:
df.iloc[:3] #11. Select the first three rows

,name,ft,zone
0,Oak,25,A
1,Pine,48,B
2,Maple,31,A


In [5]:
df[df["ft"] > 30] #12. Select rows where ft is greater than 30

,name,ft,zone
1,Pine,48,B
2,Maple,31,A
3,Cedar,60,B


13. What rows are returned by df.iloc[1:3]

The rows at positions 1 and 2, which are Pine and Maple

In [6]:
import numpy as np

points = np.array([
    [100, 200],
    [140, 230],
    [180, 260],
    [120, 280]
])

14. What does points.shape return, and what do the two numbers mean

(4, 2), meaning 4 rows and 2 columns

15. What does points[0] return

[100, 200]

16. What does points[0, 1] return

200

17. What does points[:, 0] return? Explain the colon

[100, 140, 180, 120], and the colon means select all rows

18. What does points[:, 1] return

[200, 230, 260, 280]

In [7]:
points[1:3] # 19. Return the second and third rows

array([[140, 230],
       [180, 260]])

20. Compare points[2][1] with points[2, 1]

Both return 260, but points[2, 1] is the direct NumPy row-column indexing form

21. Without running the code, determine the result of points + shift

[[110, 220], [150, 250], [190, 280], [130, 300]]

22. Why does this operation not require a Python for loop

NumPy applies the operation to the whole array using vector operations

23. Write the Boolean values stored in inside[:]

[False, True, False, True]

24. What does points[inside] return

[[140, 230], [120, 280]]

25. In GIS language, what spatial operation is this Boolean mask approximating

Selecting points inside a rectangular bounding box

26. What values are stored in classes[:]

Answer: [0, 1, 0, 1]

27. In your own words, explain the three arguments in np.where(condition, value_if_true, value_if_false)

The first argument is the condition being tested, the second is the value assigned where the condition is True, and the third is the value assigned where it's False

28. What does a - b return

[-40, -30]

29. Explain why this calculation is an example of vectorized arithmetic

NumPy subtracts, squares, and sums vector(array) values without needing a Python loop

30. What type of object is ft_array

A NumPy ndarray

31. What happened to the pandas index and column label when the Series was converted to NumPy

The pandas index and column label are not kept, leaving only the array values

32. Complete the table by describing what is being selected

Python list, locations[2]: the third item, Maple

Nested Python list, points_list[2][1]: the second value of the third point, 260

pandas DataFrame, df.iloc[2, 1]: the value in the third row and second column, 31

NumPy array, points[2, 1]: the value in the third row and second column, 260

NumPy array, points[:, 0]: all rows from the first column, the x-coordinates

33. In one sentence: what is the main indexing idea that stays the same across Python, pandas, and NumPy

Indexing uses positions or selections to access specific parts of a larger data structure

34. What becomes easier when data are arranged as a 2-D NumPy array

Selecting rows and columns and performing mathematical operations on many values at once becomes easier